[tool.ruff]
line-length = 100
target-version = "py312"

# Regras ativas
lint.select = [
  "E",  # pycodestyle (erros)
  "F",  # pyflakes (bugs)
  "I",  # imports (isort)
]

# Pastas que Ruff ignora
exclude = [
  "venv",
  ".venv",
  "__pycache__",
  "notebooks",
  "data",
  "report"
]

# Correções automáticas ON
fix = true

[tool.black]
line-length = 100
target-version = ["py312"]
